// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const UPDATE_AUTH = 'UPDATE_AUTH';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const SET_SIDEBAR = 'SET_SIDEBAR';

// Nav
export const SET_NAV1 = 'SET_NAV1';
export const SET_NAV2 = 'SET_NAV2';
export const SET_NAV3 = 'SET_NAV3';
export const REMOVE_NAV1 = 'REMOVE_NAV1';
export const REMOVE_NAV2 = 'REMOVE_NAV2';
export const REMOVE_NAV3 = 'REMOVE_NAV3';
export const SET_PAGE = 'SET_PAGE';
export const SET_ADMIN = 'SET_ADMIN';

// Products & Cart
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SET_SELECTED_ITEMS = 'SET_SELECTED_ITEMS';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
export const SET_IN_CART = 'SET_IN_CART';
export const SET_SORTED_PRODUCTS = 'SET_SORTED_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const UPDATE_PRODUCT_LIKES = 'UPDATE_PRODUCT_LIKES';
export const ADD_PRODUCT_REVIEW = 'ADD_PRODUCT_REVIEW';
export const REMOVE_PRODUCT_REVIEW = 'REMOVE_PRODUCT_REVIEW';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const HANDLE_TAGS = 'HANDLE_TAGS';
export const REMOVE_TAGS = 'REMOVE_TAGS';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const GET_ITEM = 'GET_ITEM';
export const HANDLE_DETAIL = 'HANDLE_DETAIL';
export const ADD_TO_CART = 'ADD_TO_CART';
export const OPEN_OVERVIEW = 'OPEN_OVERVIEW';
export const CLOSE_OVERVIEW = 'CLOSE_OVERVIEW';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CLEAR_CART = 'CLEAR_CART';
export const ADD_TOTALS = 'ADD_TOTALS';
export const GET_CART = 'GET_CART';
export const HANDLE_MAP = 'HANDLE_MAP';
export const ADD_TO_PRODUCTS = 'ADD_TO_PRODUCTS';
export const SET_MODAL_PRODUCTS = 'SET_MODAL_PRODUCTS';
export const INC_IMG_GALLERY = 'INC_IMG_GALLERY';
export const DEC_IMG_GALLERY = 'DEC_IMG_GALLERY';

// Variants
export const GET_VARIANTS = 'GET_VARIANTS';
export const VARIANT_ERROR = 'VARIANT_ERROR';
export const UPDATE_VARIANT_LIKES = 'UPDATE_VARIANT_LIKES';
export const DELETE_VARIANT = 'DELETE_VARIANT';
export const ADD_VARIANT = 'ADD_VARIANT';
export const GET_VARIANT = 'GET_VARIANT';
export const ADD_VARIANT_COMMENT = 'ADD_VARIANT_COMMENT';
export const REMOVE_VARIANT_COMMENT = 'REMOVE_VARIANT_COMMENT';
export const SET_SORTED_VARIANTS = 'SET_SORTED_VARIANTS';
export const SET_MODAL_VARIANTS = 'SET_MODAL_VARIANTS';
export const HANDLE_VAR_TAGS = 'HANDLE_VAR_TAGS';
export const REMOVE_VAR_TAGS = 'REMOVE_VAR_TAGS';
export const ADD_TO_VARIANTS = 'ADD_TO_VARIANTS';
export const VARIANTS_LOADING = 'VARIANTS_LOADING';
 

// Orders
export const GET_ORDER = 'GET_ORDER';
export const GET_ORDERS = 'GET_ORDERS';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const CLEAR_ORDERS = 'CLEAR_ORDERS';
export const ORDERS_LOADING = 'ORDERS_LOADING';

// Profile
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const SET_SUBS = 'SET_SUBS';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

// Store
export const GET_STORE = 'GET_STORE';
export const GET_STORES = 'GET_STORES';
export const STORE_ERROR = 'STORE_ERROR';
export const UPDATE_STORE_FAVORITES = 'UPDATE_STORE_FAVORITES';
export const ADD_STORE_REVIEW = 'ADD_STORE_REVIEW';
export const REMOVE_STORE_REVIEW = 'REMOVE_STORE_REVIEW';
export const CLEAR_STORE = 'CLEAR_STORE';
export const STORE_DELETED = 'STORE_DELETED';
export const SET_CART_STORES = 'SET_CART_STORES';
export const CLEAR_STORES = 'CLEAR_STORES';

// Collections
export const GET_COLLECTIONS = 'GET_COLLECTIONS';
export const COLLECTION_ERROR = 'COLLECTION_ERROR';
export const DELETE_COLLECTION = 'DELETE_COLLECTION';
export const UPDATE_COLLECTION_ITEMS = 'UPDATE_COLLECTION_ITEMS';
export const ADD_COLLECTION = 'ADD_COLLECTION';
export const GET_COLLECTION = 'GET_COLLECTION';
export const EDIT_COLLECTION = 'EDIT_COLLECTION';

// Locations
export const SET_LOCATIONS = 'SET_LOCATIONS';
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const LOCATION_ERROR = 'LOCATION_ERROR';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const UPDATE_LOCATION_VARIANTS = 'UPDATE_LOCATION_VARIANTS';
export const ADD_LOCATION = 'ADD_LOCATION';
export const GET_LOCATION = 'GET_LOCATION';
export const GET_PRODUCT_LOCATIONS = 'GET_PRODUCT_LOCATIONS';
export const GET_VARIANT_LOCATIONS = 'GET_VARIANT_LOCATIONS';
export const CLEAR_LOCATIONS = 'CLEAR_LOCATIONS';

// Customer
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const CUSTOMER_ERROR = 'CUSTOMER_ERROR';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const UPDATE_CUSTOMER_NAME = 'UPDATE_CUSTOMER_NAME';
export const UPDATE_CUSTOMER_ADDRESS_BOOK = 'UPDATE_CUSTOMER_ADDRESS_BOOK';
export const UPDATE_CUSTOMER_NOTES = 'UPDATE_CUSTOMER_NOTES';
export const UPDATE_CUSTOMER_TAGS = 'UPDATE_CUSTOMER_TAGS';
export const UPDATE_CUSTOMER_TOTALS = 'UPDATE_CUSTOMER_TOTALS';
export const UPDATE_CUSTOMER_ACTIVITY = 'UPDATE_CUSTOMER_ACTIVITY';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const GET_CUSTOMER = 'GET_CUSTOMER';




